# Site settings
title: Scrapy - A Fast and Powerful Scraping and Web Crawling Framework
url: "https://scrapy.org"

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8

navigation:
- text: Download
  url: download/
- text: Documentation
  url: doc/
- text: Resources
  url: resources/
- text: Community
  url: community/
- text: Commercial Support
  url: companies/

plugins:
  - jekyll-redirect-from
